version: '3.8'

services:
  php:
    build: ./php
    volumes:
      - ./../:/var/www/laravel

  nginx:
    build: ./nginx
    volumes:
      - ./../:/var/www/laravel
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  mysql:
    build: ./mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306
